### ISSUE TITLE
Images from the individual applications doesnt appear

### ISSUE THREAD

**Issue by pank789** [joeldenning/coexisting-vue-microfrontends#39] opened 2020-02-21 01:26 UTC
Hi,
When the individual app is invoked the logo/images from that module doesnt load it gives error as it takes the parent path for search and loading.

The same is seen in the sample app as well.

Can you please guide on this.

Thanks

**Comment by pankaj-naphade** [comment] 2020-02-21 07:30
It gives 404 error and link path.

http://coexisting-vue-microfrontends.surge.sh/app1/js/img/logo.png 404 (Not Found)

**Comment by pank789** [comment] 2020-02-21 10:53
It gives 404 error and link path.

http://coexisting-vue-microfrontends.surge.sh/app1/js/img/logo.png 404 (Not Found)

**Comment by joeldenning** [comment] 2020-02-22 23:38
Resolved in #40. Also this fixed the path for local development bundles - now it is like it says in the readme (http://localhost:8081/js/app.js).

**Closed** 2020-02-22 23:38 UTC

**Comment by joeldenning** [comment] 2020-02-22 23:40
I've confirmed the logo is now showing up at http://coexisting-vue-microfrontends.surge.sh/app1 after the deployment caused by #40
