### ISSUE TITLE
'app-name' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"

### ISSUE THREAD

**Issue by junaid155** [joeldenning/coexisting-vue-microfrontends#32] opened 2019-12-12 15:47 UTC
When dynamically loading vue cli app using import statement
`  singleSpa.registerApplication('
app-3', 
() =>
  import (/* webpackIgnore: true */'http://localhost:8080/app.js'), pathPrefix('/app3')); `

 causes following exception:
`Uncaught Error: 'app-3' died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"`

My sample vue main.js file looks like this:
`import Vue from vue
import App from './App.vue'
import singleSpaVue from 'single-spa-vue';
Vue.config.productionTip = true
const vueLifecycles = singleSpaVue({
  Vue,
  appOptions: {
    render: (h) => h(App)
  },
});

export const bootstrap = vueLifecycles.bootstrap;
export const mount = vueLifecycles.mount;
export const unmount = vueLifecycles.unmount;
`

**Comment by joeldenning** [comment] 2019-12-13 13:47
This error is usually caused by the webpack public path not being set “on-the-fly.” See  https://single-spa.js.org/docs/faq/#code-splits for more info.

I’m closing this since it’s not a bug in single-spa or in this example repo, but feel free to reopen or comment further.

**Closed by joeldenning** 2019-12-13 13:47 UTC

**Comment by nilesh-0608** [comment] 2023-01-24 07:01
if its vue3 then you can check below blog

https://medium.com/@nileshchavan0608/died-in-status-loading-source-code-error-in-single-spa-application-using-vue-3-js-a101a77038e6
