### ISSUE TITLE
The superposition of CSS and JS

### ISSUE THREAD

**Issue by yangangzhang** [joeldenning/coexisting-vue-microfrontends#10] opened 2019-09-23 03:09 UTC
When I switched apps, the CSS and JS of other apps that used to be active remained in the head.

I think we should remove the CSS and JS of other apps and keep only the current active's

![error3](https://user-images.githubusercontent.com/20433039/65400025-71a56680-ddf2-11e9-8665-fef6aa8ff4d0.gif)
Multiple Vue instances in the same document need to avoid global variable pollution, global monitoring pollution, style pollution and so on. Access specifications need to be formulated.

**Comment by joeldenning** [comment] 2019-09-24 03:41
> I think we should remove the CSS and JS of other apps and keep only the current active's

I agree that this is ideal. It is possible, but not very easily done. I'll explain how you can do it, but I don't think I want to add it to coexisting-vue-microfrontends as a whole.

The problem is more in webpack territory than single-spa territory. I'm almost totally sure that vue-cli uses webpack's [style-loader](https://webpack.js.org/loaders/style-loader/#root) for inserting the style elements into the dom. As far as I know, there is no built-in way to unmount the style elements created by style-loader via any webpack magick. However, I have done what you're talking about before by [setting attributes on the style elements](https://webpack.js.org/loaders/style-loader/#attributes) and then implementing a custom [single-spa unmount function](https://single-spa.js.org/docs/building-applications.html#unmount). Here's some (untested) code that is similar to what i've done in the past for this:

```js
// webpack.config.js
module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          { loader: 'style-loader', options: { attributes: { class: 'app1-styles' } } },
          { loader: 'css-loader' },
        ],
      },
    ],
  },
};
```

```js
// main.js

export const mount = [
  mountCss,
  vueLifecycles.mount,
]

export const unmount = [
  vueLifecycles.unmount,
  unmountCss,
]

let styleEls = []

function mountCss() {
  styleEls.forEach(styleEl => document.head.appendChild(styleEl))
}

function unmountCss() {
  styleEls = []
  document.querySelectorAll('.app1-styles').forEach(styleEl => {
    styleEls.push(styleEl)
    styleEl.remove()
  })
}
```

Another option is to [iterate over all the webpack modules to find the modules for the css files](https://github.com/CanopyTax/single-spa-canopy/blob/6083a631ab7351185c655b636009b9ffc5e776bf/src/single-spa-canopy.js#L131-L137) and then try to find a way to get that module to unmount its style element. If I recall correctly, that is also possible. However, it is reaching quite far into the webpack internals and a bit less desireable as a result.

I'm closing this because I think I've answered the question -- feel free to comment further or reopen.

**Closed by joeldenning** 2019-09-24 03:41 UTC
