### ISSUE TITLE
create a new div element with each click

### ISSUE THREAD

**Issue by promek** [joeldenning/coexisting-vue-microfrontends#1] opened 2019-07-26 23:14 UTC
Hi,

When I review the application demo.
each time app1 or app2 is clicked, it creates a new div element.

< div id="app1" >< /div >
< div id="app2" >< /div >
< div id="app1" >< /div >
< div id="app2" >< /div >
....

**Comment by joeldenning** [comment] 2019-07-29 16:01
This is a real bug, but a duplicate of https://github.com/CanopyTax/single-spa-vue/issues/16. I am closing this in favor of that issue

**Closed by joeldenning** 2019-07-29 16:01 UTC

**Comment by joeldenning** [comment] 2019-07-29 17:27
Fix to single-spa-vue released in https://github.com/CanopyTax/single-spa-vue/releases/tag/v1.5.3. I'll be pushing a commit to coexisting-vue-microfrontends momentarily that fixes it here, too

**Comment by promek** [comment] 2019-07-29 18:12
Thanks for your quick support.
King Regards.

**Comment by joeldenning** [comment] 2019-07-29 18:14
@promek btw i found another issue that will be released in single-spa-vue@1.5.4. See https://github.com/CanopyTax/single-spa-vue/pull/18 for more details.

**Comment by joeldenning** [comment] 2019-07-29 19:48
Updated/fixed in https://github.com/joeldenning/coexisting-vue-microfrontends/commit/ec2f7bb3b1ad7cf3a9f5ea944823a3785b5870d1
